name: Build Portal
on:
  push:
  workflow_dispatch:
  
jobs:
  build:
    name: Build ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ "linux", "darwin", "windows" ]
        arch: [ "amd64", "arm64" ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Get dependencies
        run: |
          mkdir -p $GOPATH/bin
          export PATH=$PATH:$GOPATH/bin
      - name: Build Executable
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o portal_${{ matrix.os }}_${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }} -ldflags="-s -w" -v examples/main.go
      - name: Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          path: portal_${{ matrix.os }}_${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }}
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error
          retention-days: 1
